### ISSUE TITLE
classify_by_kmers output

### ISSUE THREAD

**Issue by COMInterop** [esrice/trio_binning#11]
Dear Dr Rice:

Thank you for the nice scripts. I have a question, what are signified by columns 3 and 4 when long reads are binned?

d55a6693-7a90-4029-823a-499df63e948a	B	6.8322945	83

ef342739-729c-41f6-aead-25d9d6898c48	A	64.9068	6

3c26bec1-ad41-494e-b3a1-340236090719	B	22.774315	42

**Comment by esrice** [comment]
These are scores for haplotypes A and B, respectively. I put these there mainly for debugging purposes. The score is defined as the number of matching unique k-mers from this haplotype found in the read, multiplied by the scaling factor for that haplotype. The scaling factor in turn is defined as the total number of k-mers in the haplotype with more unique k-mers, divided by the total number of k-mers in this haplotype.

So, a quick example: let's say there are 5,000 total unique k-mers for haplotype A and 10,000 for B as determined by the short reads. Then the scaling factor for A will be 2 and for B will be 1. If a particular read has 30 k-mers from hapA and 6 from hapB, then the score will be 60 for hapA and 6 for hapB, so it will be assigned to hapA.

Let me know if you have any other questions!
