### ISSUE TITLE
Find_uniq_kmers problem

### ISSUE THREAD

**Issue by vilperte** [esrice/trio_binning#13]
Hi,

I noticed that the script `find_uniq_kmers` might have a problem when when dumping the uniq kmers to a txt file. 

It uses the `min_count` and `max_count` from the `analyze_histogram` steps. However, the max and min parameters should be passed in the beginning of the code and not by the end.

Instead of
```
dump_cmd = [kmc_cmd + '_dump', kmc_db, out_path,
                '-ci' + str(min_count), '-cx' + str(max_count)]
```

It should be
```
dump_cmd = [kmc_cmd + '_dump', '-ci' + str(min_count), '-cx' + str(max_count), 
               kmc_db, out_path]
```

**Comment by esrice** [comment]
Hi,

Thanks for the bug report. Are you actually getting an error, and if so,
what is it? Also, what version of kmc are you using? This works as written
with v3.2.1 (the current version in bioconda and the latest release on
github), so all I can think of is that earlier versions might be less
flexible with argument order.

I'll look into it further if you can give me more details.

Thanks!

**Comment by vilperte** [comment]
Thanks for the quick reply.

There is no error actually, but I was getting an uneven binning of my F1, so I tried to find what was happening.

I am indeed using an older version (v3.1.1), my fault for not checking before, sorry. But I tested now with v3.2.1 and passing the `-ci` and `-cx` parameters at the end of the command still outputs the full amount of kmers.

**Comment by esrice** [comment]
Oh, weird. Investigating now. Thanks for bringing this to my attention.

**Comment by esrice** [comment]
Oh, weird. I'll fix this tomorrow, or feel free to submit a PR. Thanks for
noticing.
