### ISSUE TITLE
Multiple species as one Hap_A  causing find unique kmers problem

### ISSUE THREAD

**Issue by sdsnature** [esrice/trio_binning#14]
I noticed if I put multiple species as Hap_A input, something went wrong on step1 'find unique kerms' while if Hap_A were set just one specie this problem won't happen, here is the report:

Counting k-mers in haplotype A...
*********************************************************************************************************************************
Stage 1: 100%
Stage 2: 100%
Computing and analyzing histogram...
in1: 100%
Traceback (most recent call last):
  File "/~/2.App/conda/env/trio_binning/bin/find-unique-kmers", line 8, in <module>
    sys.exit(main())
  File "~/2.App/conda/env/trio_binning/lib/python3.10/site-packages/trio_binning/find_unique_kmers.py", line 253, in main
    min_count, max_count = analyze_histogram(
  File "~/2.App/conda/env/trio_binning/lib/python3.10/site-packages/trio_binning/find_unique_kmers.py", line 156, in analyze_histogram
    raise HistogramError(histo_cmd)
trio_binning.find_unique_kmers.HistogramError: ['kmc_tools', 'transform', './haplotypeA', 'histogram', './9326237']

**Comment by esrice** [comment]
Sorry, I'm not sure I understand the purpose of putting multiple species as haplotype A. The idea of trio binning is that you take short reads from two unrelated or even different-species parents and long reads from their offspring, and use the short reads to separate the long reads into two bins, one for each parent. So the haplotype A and B inputs should each only contain reads from a single individual. The program will not be able to understand the haplotype A k-mer histogram if it contains sequence from multiple individuals.
