### ISSUE TITLE
Should I polishing contigs before using classify_by_alignment?

### ISSUE THREAD

**Issue by LQHHHHH** [esrice/trio_binning#2]
Hi, Edward Rice

```classify_by_alignment``` is good tool to classify Hi-c reads and RNA-seq reads. Thanks for developing.

My question is should I using tools like ```Arrow``` or  ```purge_dups``` to polish my contigs before using classify_by_alignment, or I just can directly use contigs from canu-trio. The polishing step may affect mapping rates, and I have read your paper but do not find answer.  Could you tell me should I polish contigs before using classify_by_alignment?

Thanks a lot!

**Comment by esrice** [comment]
Thanks for using my software. Polishing with arrow is a good idea before
aligning any sort of short read as it will result in better alignments. We
ran arrow twice on the original contigs output by triocanu before doing any
of the other steps. Purging haplotigs should not be necessary though, as
it's already a fully haploid assembly if trio binning worked properly.

Good luck and let me know if you have any other questions. I'll update the
readme to make this more clear.

**Comment by LQHHHHH** [comment]
Thanks for your help and suggestion. Appreciate it!
