### ISSUE TITLE
Singleton reads was found in classified bam files.

### ISSUE THREAD

**Issue by LQHHHHH** [esrice/trio_binning#3]
Hi, Edward Rice

Using your useful tool ```classify_by_alignment```, I classified my hi-c data into maternal and paternal. But, I found one of my pair-end hi-c reads in ```maternal.hi-c.bam``` and another in ```paternal.hi-c.bam```, or I found one of my reads in ```maternal.bam```  and pair reads in ```maternal.bam```. 
**Should I remove such singleton reads from my bam file?**

Now, I used ```samtools fastq -1 paternal.1.fq -2 paternal.2.fq -s paternal.singleton.fq -n paternal.hi-c.bam``` and
```samtools fastq -1 maternal.1.fq -2 maternal.2.fq -s maternal.singleton.fq -n maternal.hi-c.bam```
to transform bam to fastq files and remove singleton reads in bam files.

Thanks.

**Comment by esrice** [comment]
Yes, unpaired reads will need to be removed eventually as they don't give
any information about Hi-C links. The command you showed looks right. My
scaffolding pipeline* requires reads to be realigned unpaired, which will
generate more singletons that it later removes automatically, so it doesn't
make much difference what you do to them now.

* https://github.com/esrice/slurm-hic (not named well; it is not just for
slurm but for any platform!)

**Comment by LQHHHHH** [comment]
Nice tools and pipeline! thanks for you reply.
