### ISSUE TITLE
how to read fastq list as input?

### ISSUE THREAD

**Issue by shizhuoxing** [esrice/trio_binning#4]
hi, is there have a way to read fastq list file as input for find-unique-kmers? I found that most of the time there were multiple FASTQ files per sample after sequencing.

**Comment by esrice** [comment]
Yes, you should be able to just add more files to each of the comma-separated lists in the arguments. I used one library with one each R1 and R2 in the example in the documentation, but it doesn't treat R1 and R2 differently, so you could just do, for example:

```
find-unique-kmers -k 21 -p 8 \
    mother_lib1_R1.fastq.gz,mother_lib1_R2.fastq.gz,mother_lib2_R1.fastq.gz,mother_lib2_R2.fastq.gz \
    father_lib1_R1.fastq.gz,father_lib1_R2.fastq.gz,father_lib2_R1.fastq.gz,father_lib2_R2.fastq.gz
```

and so on for as many files as you want.
