### ISSUE TITLE
Bin hifi reads Based on Phase-Assembly

### ISSUE THREAD

**Issue by zhoudreames** [esrice/trio_binning#5]
I havent parent sequence data,so my Phased assembly gained by using self-hic data to assembly.but i want to bin my hifi reads based on my two phased assembly genome sequence, Can this be done? thanks~

**Comment by zhoudreames** [comment]
@esrice i am so sorry to disturb you,could you help me? thanks~

**Comment by esrice** [comment]
Yes, you can do this by running the steps in the section "Classifying short reads from offspring based on alignment" in the README, regardless of where your phased assemblies came from.
